dydxprotocol/v4-localization

config/localization/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
It's crashing Abacus...   
I will add a CI check to prevent this in the future.
=> Fix bad JSON

config/localization/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
=> TRCL-2899 Add FROM

config/prod/walletsV2.json, config/staging/walletsV2.json, package-lock.json, package.json, scripts/generated/app.ts
Will migrate those to v4-web in another PR
=> Update mobile wallet configs

config/localization/ja/app.json
=> Fix bad Japanese translation

config/localization/en/app.json, package-lock.json, package.json
a network nodes -> a network of nodes
=> CT-643 Fix typo

config/localizations_native/en/app.json, package-lock.json, package.json
[MOB-241 : implement pre-prompt before requesting app review](https://linear.app/dydx/issue/MOB-241/implement-pre-prompt-before-requesting-app-review)
=> MOB-241 : implement pre-prompt before requesting app review

package-lock.json, package.json
ugh version bumps are killing me. Missed the version bump that went in right before me, fixing https://github.com/dydxprotocol/v4-localization/commit/31e899c6b692358bb21fd2a1638b058457062dfc
=> fix localization package bump

config/localization/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
=> Add translation for actions

package-lock.json, package.json, scripts/generated/app.ts
forgot to do so here: https://github.com/dydxprotocol/v4-localization/pull/444
=> fix missing keys

config/localization/en/app.json, config/localizations_native/en/app.json, package-lock.json, package.json
intended to align these two copies
=> update QR code wallet connect flow code copy

config/localization/en/app.json, package-lock.json, package.json
add learn more to broadcast erorr, so FE can inject learn more link to error.
=> Equity tier broadcast error learn more

config/localization/en/app.json, package-lock.json, package.json
=> transfering -> transferring

config/localization/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
=> Orderbook grouping text

config/localization_notifications/en/app.json, package-lock.json, package.json
no block included in proposal.
=> update notification text to omit block from language

config/localization/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
make gas error generalizable to token or USDC
=> add gas fee error key, update gas error localization

config/localization/en/app.json, package-lock.json, package.json
=> fix capitalization on document

config/localization/en/app.json, package-lock.json, package.json
https://www.figma.com/design/mKevZOfE9nj6MZpiolKYW1/dYdX-%E2%80%BA-Mobile?node-id=8498-16851&t=Akhipf3STQ4I0Wzs-4
=> add "edit margin" string

config/localization_notifications/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
confirmed this change with yi, non breaking
=> update season notification localization

config/localization/en/tooltips.json, package-lock.json, package.json, scripts/generated/app.ts
=> update to ohlc tooltip

config/localizations_native/en/app.json
[design](https://www.figma.com/design/fMQodZKzn9B5aZTN5G0fLJ/dYdX-%E2%80%BA-Web?node-id=36895-2938&t=u64v5tJvv2Ut4BNB-4)
=> CLI-638 prediction markets UI pt deux

config/localization/en/app.json, package-lock.json, package.json
=> 1.1.174: update sltp strings casing

config/localization/en/tooltips.json, package-lock.json, package.json
forgot https://dydx-team.slack.com/archives/C03GKH23YAZ/p1724778889524179?thread_ts=1724697003.577059&cid=C03GKH23YAZ
=> update ohlc tooltip

config/localizations_native/en/app.json
we no longer use email in the string after [recent update](https://github.com/dydxprotocol/v4-web/commit/f24f9495dc8239d5561c43644a57805ece717cb4)
=> update compliance strings for mobile

config/localization/en/app.json, config/localization/en/tooltips.json
chatted with marketing - off-chain/on-chain/cross-chain etc should all be offchain/onchain/crosschain/etc
=> replace hyphens in -chain words

package-lock.json, package.json
no new keys, just to pull in new translations in other languages
=> chore: bump version to pull in translations

config/localization/en/tooltips.json, package-lock.json, package.json
=> fix: update tooltip strings

config/localization/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
=> chore: update untranslated wallet string

config/localizations_native/en/app.json
Apple reviewer prefers "Continue" [[link](https://linear.app/dydx/issue/BUG2-157/ios-1111-31093-rejection-by-app-store-review)]
=> Change the "Enable Camera Access" text to "Continue"

config/localization/en/app.json, package-lock.json, package.json, scripts/generated/app.ts
=> Add "Funding Rate"

config/localization/en/app.json, package-lock.json, package.json
Update rebate banner strings for October 100% free rebates
=> Update rebate banner strings for October 100% free rebates
